### ISSUE TITLE
Credential Harvester doesn't wait for the entries, instead starts a new session after pressing <return>

### ISSUE THREAD

**Issue by accessme** [trustedsec/social-engineer-toolkit#146]
Sorry i'm new in this...

**Comment by trustedsec** [comment]
Read the message right before the return =) All of the files are moved to /var/www, theres a file called harvester_* in the /var/www that records all of the entries when you submit. SET is finished at that point, which is why it goes back to the main menu. Open up a command prompt and go to /var/www and watch the harvester log.

**Comment by accessme** [comment]
I got that.....Thank you so much for replying :)
