### ISSUE TITLE
Does not Clone

### ISSUE THREAD

**Issue by saintdrug** [trustedsec/social-engineer-toolkit#149]
Hello, After installing Kali 2.0, 
when you use credential harvester to clone a site.
it clones it but seems its not putting it in the right directory resulting in when you put your ip to check if it works, it shows the apache page (default in html folder).

also, even if you manually put the index in the correct place it will load but wont work into sniffing the passwords etc..

**Comment by saintdrug** [comment]
Ok i fixed it finally, let me know if you need my config file.

**Comment by samiux** [comment]
@saintdrug ,

I would like to get the config file.  Would you please post it here or post to pastebin.com?

The developer may overlook your fix like my report previously.

Thanks.

**Comment by trustedsec** [comment]
@samiux Samiux - you sent an entire setcore.py file instead of a pull request - absolutely won't accept that.

@saintdrug - I pushed an additional check this morning where if /var/www/html already exists, it will automatically add the files to that instead of just /var/www/. You can edit the /etc/setoolkit/set.config and point the path to /var/www/html - out of convenience, added an automatic check though for the future.

**Comment by saintdrug** [comment]
trustedsec that is correct exactly what I changed that's nice to look into it and I am glad you replied, it really means a lot to see serious actions taken even for minor clarifications.
take care and glad to use ur so hard work scripts.
