### ISSUE TITLE
Don't offer to drop Kali package in favor of a git clone

### ISSUE THREAD

**Issue by rhertzog** [trustedsec/social-engineer-toolkit#172]
Commit 69176e6e8be8421d9e856aa5171604b1f95ccd1 introduced a change that we don't want in Kali.

Please do not offer the user to replace the packaged SET by a git clone of the tool... we will always patch this out on the Kali side. We are working hard to always offer the latest SET in our kali-rolling repository and users should use that if they want the greatest and latest.

Thank you.

**Comment by rhertzog** [comment]
FTR the crude removal doesn't solve anything for the user... the package is still installed so the files will come back at next upgrade. And the /usr/local/bin/setoolkit is in conflict with /usr/bin/setoolkit provided by the package, depending on the PATH configuration, the user might get a non-working one.

In the end, instead of this hack, why not get in touch with us when you find that “Kali [...] does not maintain updates well for common tools“. Send us a mail at devel@kali.org and we'll see what we can do for the specific problem you have.

**Comment by trustedsec** [comment]
We offer that as an option to the user - not a force. They don't have to use it. Packages haven't been kept up to date for several months on the SET front and I have to continually troubleshoot folks that are using out of date versions due to lag behind. If you can keep the packages up to date, I'll be happy to remove otherwise, I'm keeping it in. This isn't a hack job, this is a way to keep folks on the latest and allow them to be able to use the toolset vs. behind several months behind. I'm happy to email devel after everytime I do a new package, each time I have in the past, I haven't gotten a response back.

**Comment by rhertzog** [comment]
Keep an eye on http://pkg.kali.org/pkg/set ... 6.5.6 has been uploaded to kali-rolling one day after release. And we have a script monitoring the github releases. If you don't see your latest version in kali-rolling after a week, feel free to poke us. Somehow we missed 6.5.7, I don't know why.

We also offer them an option to use auto-built packages via kali-bleeding-edge... BTW we will shortly push 6.5.6 to the current stable release too.

**Comment by trustedsec** [comment]
How long does it take to go from bleeding to stable?

**Comment by rhertzog** [comment]
It doesn't move from bleeding to stable, it's up to the user to enable the kali-bleeding-edge repository if they want it. And you already have code for this IIRC... see bleeding_edge() in src/core/setcore.py and when they have this repository, a simple "apt-get install set/kali-bleeding-edge" will pick up the updates from this repository.

**Comment by trustedsec** [comment]
What I meant was how long before a release in SET does it take to get from there to stable?

**Comment by rhertzog** [comment]
Have a look at http://docs.kali.org/general-use/kali-linux-sources-list-repositories

People who are using kali-current (sana currently) get a new version at worst every 4 months (new stable release), but for some packages we do backport new updates that we test. And people who use kali-bleeding-edge on top of kali-current get untested daily release as soon as upstream has committed some new code...

People who are using kali-rolling get new release as soon as we upload them, usually within a week after our scripts informs us that a new version is available.

Does that answer your question ?

**Comment by trustedsec** [comment]
It does - it doesn't help the situation that most Kali users maintain kali-current and steer away from bleeding-edge. I can remove the section and default to answers that Kali is roughly 4 months behind on updates unless you switch to bleeding or upgrade to the latest. I will keep a disclaimer in there that Kali is detected, recommend switching to bleeding edge for updates since current is several months lagging behind.

**Comment by rhertzog** [comment]
OK. Ideally you display a disclaimer only if "apt-cache policy | grep -q -E 'kali-bleeding-edge|kali-rolling'" fails... and the disclaimer should invite the user either to enable kali-bleeding-edge (link: https://www.kali.org/news/bleeding-edge-kali-repositories/ ) or to switch to kali-rolling (link: http://docs.kali.org/general-use/kali-linux-sources-list-repositories )

**Comment by rhertzog** [comment]
We will probably come up with a better link for kali-bleeding-edge BTW. It needs to be properly documented on docs.kali.org so that more users can find it.

**Comment by rhertzog** [comment]
BTW, our script just warned us today of the availability of set 6.5.7. Did you push the tag only yesterday ?

**Comment by trustedsec** [comment]
Pushed tags for 6.5.8

**Comment by rhertzog** [comment]
Thanks but I don't see 6.5.8 on https://github.com/trustedsec/social-engineer-toolkit/releases (that's the page we monitor and use to download new tarballs).

But my former question was an honest question, did you push the 6.5.7 tag only yesterday or was my script missing it for two weeks for some other reason?
