### ISSUE TITLE
no harvest

### ISSUE THREAD

**Issue by ahmedbakry7272** [trustedsec/social-engineer-toolkit#174]
while using the tool on linux os and choosing web attack vectors then harvest credentials then site clone it works well and i get harvest but when i open it i find it empty pleeeeeez any help

**Comment by trustedsec** [comment]
Fixed in 6.5.9

**Comment by honoraops** [comment]
No it is not fixed yet In 6.5.9 xd

**Comment by honoraops** [comment]
But i'm sure they will fix this!

Hang on=D

**Comment by trustedsec** [comment]
It is fixed in 6.5.9:

[*] Harvester is ready, have victim browse to your site.
127.0.0.1 - - [13/Nov/2015 14:01:03] "GET / HTTP/1.1" 200 -
[*] WE GOT A HIT! Printing the output:
PARAM: GALX=5u1H7ZLdwtM
PARAM: continue=https://accounts.google.com/ManageAccount
PARAM: followup=https://accounts.google.com/ManageAccount
PARAM: _utf8=☃
PARAM: bgresponse=!_v1CsNwjdwKxomZENHgsPoF3QuMPAAQeC2hdKgG3Pu4sAlPDQ569DweFmhBJA4PfU_gZSsmqnFxTkeCPWU5Dk3tVKXMZ2wgHH6H3E00TVmKP23I9OC7qHH9QAM-oPhTQgToI4jDKrFP8WPQqWgfRCpCpeV38V1MRIwXicSu6OtYoXzlCUY6J9YYl6h4tO9D0KHtQgjlCgszUhoTknYhAubtunZWLI1R_dZghotCXAg096KkmDYxvDLALTYqHcvWjFQ_mW04gwtcbL6tCXcNAtSGcGUbRHfPVfgGt7wzOLiBCZJbG8dSy0ujn4QAnQxUj_AFl7au5I8J7uRNyRgDKnd4nk9DBhoQk1VSkVPYEls6f12xqbaTWkTedSHuS_dGF8rpUpuOjvMaMrOGp2oJ1oescqTKkKO4Wnt_1Q1z-9MYSAbquYRih7Gu6CraXvLFiJoRzvchUfdQnh5cMuqEeDE-Fg0GmlnSouxAGU5NGUmIfmMWjhXNqH5TfZEudxc6q9kJ8DH91ad02H155SLMtsxwMoL-xohqwCc5QotzuH9ACel9_4Z9kDXSmk10P_6iEw0Ip-j4V1fbz106ISGXOi64ZAYsvEa7xLq3Ygzr_KXjsQcDsqA
PARAM: pstMsg=1
PARAM: dnConn=
PARAM: checkConnection=
PARAM: checkedDomains=youtube
POSSIBLE USERNAME FIELD FOUND: Email=testing
POSSIBLE PASSWORD FIELD FOUND: Passwd=testing
PARAM: signIn=Sign+in
PARAM: PersistentCookie=yes
PARAM: rmShown=1
[*] WHEN YOU'RE FINISHED, HIT CONTROL-C TO GENERATE A REPORT.
