### ISSUE TITLE
Using DNS with SET

### ISSUE THREAD

**Issue by AngryBananer** [trustedsec/social-engineer-toolkit#181]
First of all thanks for your great tool and fast help, but could you explain me a liddle bit more what you mean with "Use the HTTPS module for that", because i dind't  found anything like that.
I like to create an undetectable Payload with the Powershell Alphanumeric Shellcode Injector.
It must not be with Powershell but it should be undetectable (where the Powershell Alphanumeric Shellcode Injector is the best way from my point of view) and it must go over an DNS...

Thanks for your patience with me ;)

https://github.com/trustedsec/social-engineer-toolkit/issues/176

**Comment by trustedsec** [comment]
There's no way to tunnel a shell over DNS unless you do something custom like dnscat2 or something like Corelans unofficial DNS meterpreter. If you are looking to use hostnames for your shell, when SET prompts you for the LHOST option, you would specify a hostname instead of an IP. SET supports hostnames or IP addresses in the field for the LHOST lookup field as long as the payload supports it. The SET Interactive Shell, Meterpreter, and everything else should support hostnames.
