### ISSUE TITLE
Credential Harvester

### ISSUE THREAD

**Issue by kevinclaassens** [trustedsec/social-engineer-toolkit#249]
When I try and use the credential harvester on a cloned site setoolkit just shows [*] This could take a little bit... and the after that the menu automatically appears. I have also checked to see if apache is running

**Comment by trustedsec** [comment]
Be sure you have an Internet connection and that you aren't running through a proxy. Use set-proxy if that is the case. Works fine on the latest version:

set:webattack> Enter the url to clone:https://gmail.com

[*] Cloning the website: https://accounts.google.com
[*] This could take a little bit...

The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] Apache is set to ON - everything will be placed in your web root directory of apache.
[*] Files will be written out to the root directory of apache.
[*] ALL files are within your Apache directory since you specified it to ON.
Apache webserver is set to ON. Copying over PHP file to the website.
Please note that all output from the harvester will be found under apache_dir/harvester_date.txt
Feel free to customize post.php in the /var/www/html directory
[*] All files have been copied to /var/www/html
[*] SET is now listening for incoming credentials. You can control-c out of this and completely exit SET at anytime and still keep the attack going.
[*] All files are located under the Apache web root directory: /var/www/html
[*] All fields captures will be displayed below.
[Credential Harvester is now listening below...]
