### ISSUE TITLE
Apache and Setoolkit

### ISSUE THREAD

**Issue by nicolaynicolavich** [trustedsec/social-engineer-toolkit#299]
I have put setoolkit on mac some time ago, today i was to try and play around with it. When i did a site clone in mentioned that the apache got turned on, nevertheless, i could not connect to my ip. Any reason why? Could it work with the apache off? I am quite new with this so explain answer in simple terms. thnx

**Comment by trustedsec** [comment]
No sweat, happy to explain. OSX is a bitch challenging because it isn't a server-based OS really. Based on BSD - Linux-based OS's are more preferred when using SET however it will work. I would recommend editing the /etc/setoolkit/set.config and turning APACHE_SERVER=ON to APACHE_SERVER=OFF, this will use the built-in web server. For longer term campaigns I would recommend dedicated Linux installs (debian/ubuntu preferred). 

Hope that helps and happy to answer any questions you have. Closing this one out, but if you comment, I'll get notifications.
