### ISSUE TITLE
social-engineer-toolkit package for Arch Linux

### ISSUE THREAD

**Issue by shibumi** [trustedsec/social-engineer-toolkit#333]
Hello everybody,
I have pushed my first version of your SET in the AUR (Arch Linux User Repository) and i want some feedback. Which optional dependencies or hard dependencies am I missing? Is this the right way to install it? Many questions.. Here is the package:

https://aur.archlinux.org/packages/social-engineer-toolkit/ 

would be nice to get some feedback. The PKGBUILD looks like this:

```
#Maintainer: Christian Rebischke <chris.rebischke[at]archlinux[dot]org>

pkgname="social-engineer-toolkit"
pkgver=7.4.2
pkgrel=1
pkgdesc="The Social-Engineer Toolkit (SET)"
arch=("any")
url="https://github.com/trustedsec/social-engineer-toolkit"
license=("custom")
makedepends=("python2")
depends=("python2-pexpect" "python2-crypto" "python2-requests"
         "python2-pyopenssl" "python2-pefile" "impacket" 
         "python2-pillow" "python2-qrcode" "python2-beautifulsoup3")
optdepends=("metasploit")
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/trustedsec/social-engineer-toolkit/archive/${pkgver}.tar.gz"
        "setoolkit")
sha512sums=('067e3e6b1ceffdc7804fed2055a95cf482f8efa22b4e94bcd898f390297403a1bbf79743e06d6d71653e4c8dd74e2a3825819023a735314ace672dbe9ba6898e'
            '130df5c3be2a75466933c086a10194a8e276b699698389af1528d2aa0f445d1dd41a82bf27e01749d59481df3d1071ac37605c4ee3e57c8bf99dd2410dd23a0b')

build() {
  cd "${pkgname}-${pkgver}"
  python2 -m compileall .
  python2 -O -m compileall . 
}

package() {
  mkdir -p "${pkgdir}/usr/share/setoolkit"
  install -D -m755 "${srcdir}/setoolkit" "${pkgdir}/usr/bin/setoolkit"
  cd "${pkgname}-${pkgver}"
  cp -r * "${pkgdir}/usr/share/setoolkit"
}
```

Best regards,

Chris

**Comment by L1ghtn1ng** [comment]
Set is capable of using python 3, so I would get it to use that instead of python 2. I would say that metasploit is more of a hard dependency. I would also go with that you should actually not need to compile anything if all the packages set needs are in the arch repos.



On Sun, Nov 27, 2016 at 6:37 PM +0000, "Christian Rebischke" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello everybody,
I have pushed my first version of your SET in the AUR (Arch Linux User Repository) and i want some feedback. Which optional dependencies or hard dependencies am I missing? Is this the right way to install it? Many questions.. Here is the package:

https://aur.archlinux.org/packages/social-engineer-toolkit/

would be nice to get some feedback. The PKGBUILD looks like this:

#Maintainer: Christian Rebischke <chris.rebischke[at]archlinux[dot]org>

pkgname="social-engineer-toolkit"
pkgver=7.4.2
pkgrel=1
pkgdesc="The Social-Engineer Toolkit (SET)"
arch=("any")
url="https://github.com/trustedsec/social-engineer-toolkit"
license=("custom")
makedepends=("python2")
depends=("python2-pexpect" "python2-crypto" "python2-requests"
         "python2-pyopenssl" "python2-pefile" "impacket"
         "python2-pillow" "python2-qrcode" "python2-beautifulsoup3")
optdepends=("metasploit")
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/trustedsec/social-engineer-toolkit/archive/${pkgver}.tar.gz"
        "setoolkit")
sha512sums=('067e3e6b1ceffdc7804fed2055a95cf482f8efa22b4e94bcd898f390297403a1bbf79743e06d6d71653e4c8dd74e2a3825819023a735314ace672dbe9ba6898e'
            '130df5c3be2a75466933c086a10194a8e276b699698389af1528d2aa0f445d1dd41a82bf27e01749d59481df3d1071ac37605c4ee3e57c8bf99dd2410dd23a0b')

build() {
  cd "${pkgname}-${pkgver}"
  python2 -m compileall .
  python2 -O -m compileall .
}

package() {
  mkdir -p "${pkgdir}/usr/share/setoolkit"
  install -D -m755 "${srcdir}/setoolkit" "${pkgdir}/usr/bin/setoolkit"
  cd "${pkgname}-${pkgver}"
  cp -r * "${pkgdir}/usr/share/setoolkit"
}


Best regards,

Chris

**Comment by shibumi** [comment]
Hey,
Thanks for your reply. Switching to python3 is a good idea. I wanted to make sure that it's running. I was unsure about python3.  I will also add metasploit to the hard dependencies. Do I want something else as hard oder optional dependency?

**Comment by trustedsec** [comment]
Everything else looks great...  Thanks =)
