### ISSUE TITLE
OpenSSL not working

### ISSUE THREAD

**Issue by Samuel-Campbell** [trustedsec/social-engineer-toolkit#340]
I'm on arch linux and it seems like there is a problem when using OpenSSL
I have tried opening a python script and writing: 
"From OpenSSL import SSL"
This works...
However I still get the error when using Setoolkit

"Python OpenSSL wasn't detected or has an installation issue, note that SSL compatibility is now turned off"

When I remove the "from OpenSSL import SSL" from the try/catch block, it says that :

TypeError: 'function' object is not iterable

That is in line 411 of pkgutil.py, in get_importer

**Comment by jeretc** [comment]
Openssl seem to be an issue with kali and parrotsec. Ive tried setoolkit on both OS same issue.

**Comment by Samuel-Campbell** [comment]
I'm on Arch Linux

**Comment by Samuel-Campbell** [comment]
So If I understand this correctly then not being able to use OpenSSL means that we can't use setoolkit to simulate HTTPS websites right?

**Comment by trustedsec** [comment]
It's actually not a SET issue in any shape. You wouldn't want to remove the try/except since it would no longer import pyopenssl which is needed in order for SSL to work in Python.

Honestly, the only time that this will be triggered is when you have apache_server to OFF and using the webattack with SSL. If you turn apache_server to on this isn't an issue.

It *looks* to be a broken package and not properly allowing import of the module. As mentioned before in other issues this works perfectly fine on Debian and Ubuntu without error.

**Comment by trustedsec** [comment]
Okay, so I decided to download Kali and Fedora just to test these out. It isn't a "problem" with Kali or Fedora but more so an import link bug in pyopenssl. Why Ubuntu/Debian isn't impacted, have no idea. I've submitted a patch but in the meantime I have a workaround and already committed it into SET. If you git pull, it should address it regardless. Considering this issue now closed.
