### ISSUE TITLE
Why is this happening and how do i get it like that?

### ISSUE THREAD

**Issue by Preeqo** [trustedsec/social-engineer-toolkit#444]
when i try cloning a web site this pops up 
![why hass it](https://user-images.githubusercontent.com/28513012/28501950-8211a688-6fdf-11e7-9e68-c56dc04daa52.PNG)
and when i try turning on apache this come up

![seeeee](https://user-images.githubusercontent.com/28513012/28501969-fa2f77da-6fdf-11e7-9ba5-5d87a7b4f0f1.PNG)
and when i press no it takes me back 
 and this is what happens when i press yes 
![seeeeeeee](https://user-images.githubusercontent.com/28513012/28501973-0b817006-6fe0-11e7-982d-fd6a88cebaff.PNG)

where as for other people this comes up
![whyyyy 2](https://user-images.githubusercontent.com/28513012/28501946-691b0fb6-6fdf-11e7-967a-8d1f405b5fa2.PNG)

i've asked before and you told me this " If you want to use apache and not use the built in web server you can edit /etc/setoolkit/set.config and turn APACHE_SERVER=OFF to APACHE_SERVER=ON" 

i dont fully understand what you mean by it, if you could help that would be great

**Comment by Preeqo** [comment]
also how do u update setoolkit again, i have for got

**Comment by trustedsec** [comment]
If you are using Kali, I would recommend turning bleeding edge repos on in order to receive the latest updates. That will ensure you are running fairly recent builds ( I think they do it daily or weekly so it should be pretty current ). By using apt-get update, apt-get dist-upgrade should get you to the latest version.

When I said turn APACHE_SERVER to ON, you will need to edit the file which is located under /etc/setoolkit/set.config.

A good tutorial on learning editors can be found here:

http://staffwww.fullcoll.edu/sedwards/Nano/IntroToNano.html

**Comment by Preeqo** [comment]
okay thank you ill give it ago now
