### ISSUE TITLE
Credential harvester not redirecting properly on changing web server port

### ISSUE THREAD

**Issue by chrisstone07** [trustedsec/social-engineer-toolkit#469]
**Expected Behaviour**

So basically I'm trying to clone Instagram login, I've got the custom site clone and all files are copied. Everything works fine when the web server port is set to 80 but when I change it to some other port in the set.config file the website doesn't redirect properly to the original one. I get this

<HTML><head><meta refresh content='0'; URL = http://www.Instagram.com>

Also when I use it with ngrok i get 502 bad gateway error on clicking login instead of taking me to the original site.

**Set Version**

_Set version_
7.7(latest)
And yeah I'm using Kali rolling 2017.2

**Comment by trustedsec** [comment]
Very possible that this is due to the site you are cloning. I am able to clone properly and switch the port. Screenshot attached below:

<img width="1378" alt="screen shot 2017-10-03 at 11 56 49 am" src="https://user-images.githubusercontent.com/3160808/31135092-04e97466-a832-11e7-85e6-b383817af729.png">
