### ISSUE TITLE
credential harvester not working correctly

### ISSUE THREAD

**Issue by Exotic-Algorithms** [trustedsec/social-engineer-toolkit#520]
**Expected Behaviour**

set:webattack> IP address for the POST back in Harvester/Tabnabbing [192.168.1.10]:192.168.1.10        
[-] SET supports both HTTP and HTTPS
[-] Example: http://www.thisisafakesite.com
set:webattack> Enter the url to clone:www.facebook.com

[*] Cloning the website: https://login.facebook.com/login.php
[*] This could take a little bit...

The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:
[*] Filename obfuscation complete. Payload name is: SfHG0W4CCOA
[*] Malicious java applet website prepped for deployment

**Actual Behaviour**

set:webattack> IP address for the POST back in Harvester/Tabnabbing [192.168.1.10]:192.168.1.10        
[-] SET supports both HTTP and HTTPS
[-] Example: http://www.thisisafakesite.com
set:webattack> Enter the url to clone:www.facebook.com

[*] Cloning the website: https://login.facebook.com/login.php
[*] This could take a little bit...

The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:

**Set Version**

7.7.5

```
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
````

**Comment by Exotic-Algorithms** [comment]
i let it run for 30 minutes before giving up. I'v tried everything. Updating the app, updating kali, reinstalling the app, running the app on both windows and ubuntu. NOTHING works.

**Comment by Maxterino** [comment]
I have the same problem but then with cloning the site. Im sorry but i can't help you. I hope someone finds a solution to this problem and mine

**Comment by MASK7LJ** [comment]
cloning is not working..!
showing this -->>  
[*] This could take a little bit...

The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:

**Comment by championkali** [comment]
[*] Error. Unable to clone this specific site. Check your internet connection.
I have update my kali  Version: 7.7.5
serious i have try everything can someone help

**Comment by championkali** [comment]
[*] Error. Unable to clone this specific site. Check your internet connection.
I have update my kali Version: 7.7.5
serious i have try everything can someone help
You cannot clone any website for any pent test and please can someone help

**Comment by trustedsec** [comment]
I'm unable to reproduce these - the sites you clone have to have a username and password field in order for it to rewrite. You can conversely import your own website that has POST parameters in order to use. Additionally when using credential harvester, you will need to specify the external address, not your NAT address if you want POSTs to work properly from the Internet. Also need to setup port forwarding if you aren't using a public IP box. Basic networking stuff.

**Comment by briancanspit** [comment]
I am running Kali Linux in a virtual machine (the Kali rolling) version, and i wanted to use the Web Credentials Harvester but i am unable to get credentials for people not on my network. I read tons of journals about Port forwarding but none of them have been as descriptive as I'd like, thus the reason for my failure. Somehow i just can't seem to get it right. Please assist.

**Comment by aryxnkxushik** [comment]
Use ngrok for port forwarding, just google ngrok its pretty easy and free.

> I am running Kali Linux in a virtual machine (the Kali rolling) version, and i wanted to use the Web Credentials Harvester but i am unable to get credentials for people not on my network. I read tons of journals about Port forwarding but none of them have been as descriptive as I'd like, thus the reason for my failure. Somehow i just can't seem to get it right. Please assist.

**Comment by briancanspit** [comment]
> Use ngrok for port forwarding, just google ngrok its pretty easy and free.
> 
> > I am running Kali Linux in a virtual machine (the Kali rolling) version, and i wanted to use the Web Credentials Harvester but i am unable to get credentials for people not on my network. I read tons of journals about Port forwarding but none of them have been as descriptive as I'd like, thus the reason for my failure. Somehow i just can't seem to get it right. Please assist.

I got it working ages ago. Thanks anyway.

**Comment by rinxhen17** [comment]
I have same issue but I doesn't work even if its on local network. It gives back email address but doesn't show password. any help appreciated please

**Comment by snakepeek** [comment]
[*] Cloning the website: http://www.google.com
[*] This could take a little bit...

The Web Attack module is a unique way of utilizing multiple web-based attacks in order to compromise the intended victim.

The Java Applet Attack method will spoof a Java Certificate and deliver a metasploit based payload. Uses a customized java applet created by Thomas Werth to deliver the payload.

The Metasploit Browser Exploit method will utilize select Metasploit browser exploits through an iframe and deliver a Metasploit payload.

The Credential Harvester method will utilize web cloning of a web- site that has a username and password field and harvest all the information posted to the website.

The TabNabbing method will wait for a user to move to a different tab, then refresh the page to something different.
---
this is the error im getting.
