### ISSUE TITLE
Exception happened during processing of request from ('xxxxxx', xxxxx) Traceback (most recent call last):   File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread     self.finish_request(request, client_address)   File "/usr/lib/pytho

### ISSUE THREAD

**Issue by user5001** [trustedsec/social-engineer-toolkit#742]
HELP PLEASE IM USING KALI LINUX SETOOLKIT ERROR Credential Harvester Attack
Please Help me !!!
Exception happened during processing of request from ('192.168.1.5', 57954)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/set/src/webattack/harvester/harvester.py", line 334, in do_POST
    filewrite.write(cgi.escape("PARAM: " + line + "\n"))
AttributeError: module 'cgi' has no attribute 'escape'

**Comment by agan19** [comment]
Same issue here, any fixes?

**Comment by User-cifra** [comment]
The same issue, what can I do?

**Comment by CRO-THEHACKER** [comment]
See if running:

`pip install cgi`

fixes it, if not its a code prob.

**Comment by Bowser1704** [comment]
> See if running:
> 
> `pip install cgi`
> 
> fixes it, if not its a code prob.

Does it work?
```bash
#pip install cgi
ERROR: Could not find a version that satisfies the requirement cgi (from versions: none)
ERROR: No matching distribution found for cgi
```
so any fixes?

**Comment by User-cifra** [comment]
This appears in the terminal: #pip install cgiERROR: Could not find a version that satisfies the requirement cgi (from versions: none)ERROR: No matching distribution found for cgi  Sent from Mail for Windows 10 From: BowserSent: domingo, 17 de mayo de 2020 10:33 p. m.To: trustedsec/social-engineer-toolkitCc: User-cifra; CommentSubject: Re: [trustedsec/social-engineer-toolkit] Exception happened during processing of request from ('xxxxxx', xxxxx) Traceback (most recent call last): File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread self.finish_request(request, client_address) File "/usr/lib/pytho (#742) See if running:pip install cgifixes it, if not its a code prob.Does it work?#pip install cgiERROR: Could not find a version that satisfies the requirement cgi (from versions: none)ERROR: No matching distribution found for cgiso any fixes?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Bowser1704** [comment]
There is already a pr to fix it.
Changing package cgi to package html.
Haven’t been merged.

**Comment by jamt0** [comment]
same error, 

> There is already a pr to fix it.
> Changing package cgi to package html.
> Haven’t been merged.

same error, i did it

**Comment by reseeman** [comment]
> same error,
> 
> > There is already a pr to fix it.
> > Changing package cgi to package html.
> > Haven’t been merged.
> 
> same error, i did it

how can I change cgi on html?

**Comment by HackingDave** [comment]
Fixed.
